name: Generate index.html

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate index.html
        run: |
          repo_dir=$(pwd)
          output_file="$repo_dir/index.html"

          # HTML header 部分
          echo "<html><head><title>huyixi's Internet Archive</title><link rel=\"stylesheet\" href=\"css/index.css\"></head><body>" > $output_file
          echo "<h1>huyixi's Internet Archive</h1>" >> $output_file
          echo "<ul>" >> $output_file

          # Create a temporary file to store file paths and dates
          temp_file=$(mktemp)

          # Find HTML files and get their dates
          find $repo_dir -type f -name "*.html" ! -name "index.html" | while read file; do
            rel_path=$(realpath --relative-to="$repo_dir" "$file")

            echo "DEBUG: Processing file: $file"

            # 使用perl处理多行HTML注释
            html_comment=$(perl -0777 -ne 'print $& if /<!--[\s\S]*?-->/g' "$file")
            echo "DEBUG: Found HTML comment: $html_comment"

            # 从注释中提取日期
            date_from_file=$(echo "$html_comment" | perl -ne 'print $1 if /date: ?(\d{4}[-\/]\d{2}[-\/]\d{2})/')
            echo "DEBUG: Extracted date: $date_from_file"

            if [ ! -z "$date_from_file" ]; then
              # 统一日期格式，将斜杠替换为横杠
              date_from_file=$(echo "$date_from_file" | sed 's|/|-|g')
              timestamp=$(date -d "$date_from_file" +%s)
              echo "DEBUG: Formatted date: $date_from_file"
              echo "DEBUG: Generated timestamp: $timestamp"
            else
              echo "DEBUG: No date found in HTML comment"
            fi

            echo "$timestamp|$rel_path|$date_from_file" >> $temp_file
          done

          # Sort by timestamp (newest first) and generate HTML links
          sort -rn $temp_file | while IFS='|' read -r timestamp path date_from_file; do
            if [ ! -z "$date_from_file" ]; then
              display_date=$date_from_file
            else
              display_date=$(date -d "@$timestamp" +"%Y-%m-%d")
            fi
            echo "<li><a href=\"$path\">$path</a> <span class=\"date\">$display_date</span></li>" >> $output_file
          done

          # Clean up temporary file
          rm $temp_file

          echo "</ul>" >> $output_file
          echo "</body></html>" >> $output_file

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update index.html with new HTML files"
          git push
